--- #YAML:1.0
name:                Math-Random-AcceptReject
version:             0.01
abstract:            Acceptance-Rejection PDF transformations
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Math::Symbolic:                0.504
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Steffen Müller <smueller@cpan.org>
